---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv2
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "gp2"
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-015d7e6baa221fd32
