---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-vol1
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnly
  storageClassName: "gp2"
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: vol-085ef758fbd42bdd1
