apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: exampleextsecret
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: kube-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: mihailo_nextcloud_secrets
